### ISSUE TITLE
Local build is failing

### ISSUE THREAD

**Issue by krisztianb** [jDataView/jBinary#67]
I cloned the GIT repo and installed the NPM packages using `npm install`.

Then I did this in a command window on Windows:

```sh
C:\MyProjects\code\jBinary>npx grunt
npx: installed 196 in 15.814s
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined

Running "build" task

Running "newer:lintspaces" (newer) task

Running "newer:lintspaces:all" (newer) task

Running "lintspaces:all" (lintspaces) task
>> 59 lint free.

Running "newer-postrun:lintspaces:all:1:C:\MyProjects\code\jBinary\node_modules\grunt-newer\.cache" (newer-postrun) task

Running "newer:jshint:grunt" (newer) task

Running "jshint:grunt" (jshint) task
Warning: The "path" argument must be of type string. Received null Use --force to continue.

Aborted due to warnings.
```

I've never used Grunt before so maybe `npx grunt` is not what I need to execute?

**Comment by krisztianb** [comment]
Ok. After reading some Grunt docs I installed `grunt-cli` via NPM. Now I don't have to use `npx` anymore, but still get the same error message.

```sh
Loading "grunt-karma.js" tasks...ERROR
> TypeError: Cannot read property 'prototype' of undefined
```

However I can't find any file name `grunt-karma.js`. Could it be that this is what the error message is trying to tell me?

**Comment by krisztianb** [comment]
I managed to get a verbose output:

```sh
C:\MyProjects\code\jBinary>grunt node -v
Initializing
Command-line options: --verbose, --gruntfile=C:\MyProjects\code\jBinary\Gruntfile.js

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading src/.jshintrc...OK
Parsing src/.jshintrc...OK
Initializing config...OK

Registering "grunt-bump" local Npm module tasks.
Reading C:\MyProjects\code\jBinary\node_modules\grunt-bump\package.json...OK
Parsing C:\MyProjects\code\jBinary\node_modules\grunt-bump\package.json...OK
Loading "bump.js" tasks...OK
+ bump, bump-commit, bump-only

Registering "grunt-compare-size" local Npm module tasks.
Reading C:\MyProjects\code\jBinary\node_modules\grunt-compare-size\package.json...OK
Parsing C:\MyProjects\code\jBinary\node_modules\grunt-compare-size\package.json...OK
Loading "compare-size.js" tasks...OK
+ compare_size, compare_size:add, compare_size:empty, compare_size:list, compare_size:prune, compare_size:remove, compare_size_add, compare_size_empty, compare_size_list, compare_size_remove

Registering "grunt-concat-sourcemap" local Npm module tasks.
Reading C:\MyProjects\code\jBinary\node_modules\grunt-concat-sourcemap\package.json...OK
Parsing C:\MyProjects\code\jBinary\node_modules\grunt-concat-sourcemap\package.json...OK
Loading "concat_sourcemap.js" tasks...OK
+ concat_sourcemap

Registering "grunt-contrib-clean" local Npm module tasks.
Reading C:\MyProjects\code\jBinary\node_modules\grunt-contrib-clean\package.json...OK
Parsing C:\MyProjects\code\jBinary\node_modules\grunt-contrib-clean\package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-contrib-jshint" local Npm module tasks.
Reading C:\MyProjects\code\jBinary\node_modules\grunt-contrib-jshint\package.json...OK
Parsing C:\MyProjects\code\jBinary\node_modules\grunt-contrib-jshint\package.json...OK
Loading "jshint.js" tasks...OK
+ jshint

Registering "grunt-contrib-uglify" local Npm module tasks.
Reading C:\MyProjects\code\jBinary\node_modules\grunt-contrib-uglify\package.json...OK
Parsing C:\MyProjects\code\jBinary\node_modules\grunt-contrib-uglify\package.json...OK
Loading "uglify.js" tasks...OK
+ uglify

Registering "grunt-contrib-watch" local Npm module tasks.
Reading C:\MyProjects\code\jBinary\node_modules\grunt-contrib-watch\package.json...OK
Parsing C:\MyProjects\code\jBinary\node_modules\grunt-contrib-watch\package.json...OK
Loading "watch.js" tasks...OK
+ watch

Registering "grunt-karma" local Npm module tasks.
Reading C:\MyProjects\code\jBinary\node_modules\grunt-karma\package.json...OK
Parsing C:\MyProjects\code\jBinary\node_modules\grunt-karma\package.json...OK
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
>>     at Object.<anonymous> (C:\MyProjects\code\jBinary\node_modules\socket.io\lib\store.js:35:42)
>>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>>     at Module.load (internal/modules/cjs/loader.js:928:32)
>>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>>     at Module.require (internal/modules/cjs/loader.js:952:19)
>>     at require (internal/modules/cjs/helpers.js:88:18)
>>     at Object.<anonymous> (C:\MyProjects\code\jBinary\node_modules\socket.io\lib\manager.js:16:13)
>>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

Registering "grunt-lintspaces" local Npm module tasks.
Reading C:\MyProjects\code\jBinary\node_modules\grunt-lintspaces\package.json...OK
Parsing C:\MyProjects\code\jBinary\node_modules\grunt-lintspaces\package.json...OK
Loading "lintspaces.js" tasks...OK
+ lintspaces

Registering "grunt-mocha-test" local Npm module tasks.
Reading C:\MyProjects\code\jBinary\node_modules\grunt-mocha-test\package.json...OK
Parsing C:\MyProjects\code\jBinary\node_modules\grunt-mocha-test\package.json...OK
Loading "mocha-test.js" tasks...OK
+ mochaTest

Registering "grunt-newer" local Npm module tasks.
Reading C:\MyProjects\code\jBinary\node_modules\grunt-newer\package.json...OK
Parsing C:\MyProjects\code\jBinary\node_modules\grunt-newer\package.json...OK
Loading "newer.js" tasks...OK
+ any-newer, newer, newer-clean, newer-postrun
Loading "Gruntfile.js" tasks...OK
+ browser, build, build_common, default, live, node, npm_publish, test

Running tasks: node

Running "node" task

Running "build:node" (build) task

Running "build_common" task

Running "newer:lintspaces" (newer) task

Running "newer:lintspaces:all" (newer) task
Options: cache="C:\\MyProjects\\code\\jBinary\\node_modules\\grunt-newer\\.cache", override=undefined
Files: grunt, grunt/aliases.yml, grunt/build.js, grunt/bump.js, grunt/clean.js, grunt/compare_size.js, grunt/concat_sourcemap.js, grunt/jshint.js, grunt/karma.js, grunt/lintspaces.js, grunt/mochaTest.js, grunt/npm_publish.js, grunt/test.js, grunt/uglify.js, grunt/watch.js, src, src/.jshintrc, src/core.js, src/io, src/io/load.js, src/io/save.js, src/proto, src/proto/as.js, src/proto/cache.js, src/proto/context.js, src/proto/position.js, src/proto/props.js, src/shim.js, src/template.js, src/type.js, src/typeSet, src/typeSet/_simpleTypes.js, src/typeSet/array.js, src/typeSet/binary.js, src/typeSet/bitfield.js, src/typeSet/blob.js, src/typeSet/const.js, src/typeSet/enum.js, src/typeSet/extend.js, src/typeSet/if.js, src/typeSet/ifNot.js, src/typeSet/lazy.js, src/typeSet/object.js, src/typeSet/skip.js, src/typeSet/string.js, src/typeSet/string0.js, src/utils.js, test, test/123.tar, test/karma.conf.js, test/karma.mocha.conf.js, test/mocha.opts, test/test.js, umd, umd/footer.js, umd/header.js, .editorconfig, .git, .gitignore, .travis.yml, Gruntfile.js, MIT-license.txt, README.md, component.json, dist, node_modules, package-lock.json, package.json, travis_after_all.py
No newer files to process.

Running "newer:jshint:grunt" (newer) task
Options: cache="C:\\MyProjects\\code\\jBinary\\node_modules\\grunt-newer\\.cache", override=undefined
Files: grunt/build.js, grunt/bump.js, grunt/clean.js, grunt/compare_size.js, grunt/concat_sourcemap.js, grunt/jshint.js, grunt/karma.js, grunt/lintspaces.js, grunt/mochaTest.js, grunt/npm_publish.js, grunt/test.js, grunt/uglify.js, grunt/watch.js

Running "jshint:grunt" (jshint) task
Verifying property jshint.grunt exists in config...OK
Files: grunt/build.js, grunt/bump.js, grunt/clean.js, grunt/compare_size.js, grunt/concat_sourcemap.js, grunt/jshint.js, grunt/karma.js, grunt/lintspaces.js, grunt/mochaTest.js, grunt/npm_publish.js, grunt/test.js, grunt/uglify.js, grunt/watch.js -> [no dest]
Options: force=false, reporterOutput=null, browser, node, nonstandard, worker, globals={"define":false,"URL":false,"File":false,"FileReaderSync":false,"Promise":false,"VBArray":false,"jDataView":false,"NODE":false,"BROWSER":false}, camelcase=false, curly, eqeqeq, es3=false, expr, immed, indent=4, lastsemic, latedef, laxbreak, newcap=false, noarg, noempty, nonew, quotmark="single", smarttabs, trailing, undef, reporter="C:\\MyProjects\\code\\jBinary\\node_modules\\jshint-stylish\\stylish.js"
Warning: The "path" argument must be of type string. Received null Use --force to continue.

Aborted due to warnings.
```

**Comment by krisztianb** [comment]
Ok, so `grunt-karma` is some sort of NPM module that this project uses and the file producing the error is located here: `C:\MyProjects\code\jBinary\node_modules\grunt-karma\tasks\grunt-karma.js`

I guess this error is some sort of internal node thing and is a result of the outdated dependencies.
